services:
  mysqldatabase:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  test:
    image: emilyyy0621/testrepository:test-image
#    image: test-image
    ports:
      - 8000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldatabase:3306/testdb
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysqldatabase:
        condition: service_healthy