name: Docker
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: emilyyy0621
          password: 93f963e6-8bc5-4bc4-888c-8a43b817098e
          repository: emilyyy0621/testrepository
          tags: test-image

#      - name: Build image
#        run: docker build -t test-image .
#
#      - name: Create tag
#        run: docker tag test-image emilyyy0621/testrepository:test-image
#
#
#      - name: Push image on repository
#        run: docker push emilyyy0621/testrepository:test-image
